### ISSUE TITLE
Import cloudpathlib fails when google-api-core is installed

### ISSUE THREAD

**Issue by SichongP** [drivendataorg/cloudpathlib#335]
A library I use has `google-api-core` as a dependency. I have `cloudpathlib-s3` installed but not `cloudpathlib-gs` because I don't need GS functionalities.

However, in this setup, importing cloudpathlib leads to error:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/sichong/anaconda3/envs/smk_dev/lib/python3.11/site-packages/cloudpathlib/__init__.py", line 8, in <module>
    from .gs.gspath import GSPath
  File "/Users/sichong/anaconda3/envs/smk_dev/lib/python3.11/site-packages/cloudpathlib/gs/__init__.py", line 1, in <module>
    from .gsclient import GSClient
  File "/Users/sichong/anaconda3/envs/smk_dev/lib/python3.11/site-packages/cloudpathlib/gs/gsclient.py", line 16, in <module>
    from google.api_core.exceptions import NotFound
  File "/Users/sichong/anaconda3/envs/smk_dev/lib/python3.11/site-packages/google/api_core/exceptions.py", line 29, in <module>
    from google.rpc import error_details_pb2
  File "/Users/sichong/anaconda3/envs/smk_dev/lib/python3.11/site-packages/google/rpc/error_details_pb2.py", line 20, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/Users/sichong/anaconda3/envs/smk_dev/lib/python3.11/site-packages/google/protobuf/descriptor.py", line 51, in <module>
    from google.protobuf.pyext import _message
ImportError: dlopen(/Users/sichong/anaconda3/envs/smk_dev/lib/python3.11/site-packages/google/protobuf/pyext/_message.cpython-311-darwin.so, 0x0002): Library not loaded: @rpath/libprotobuf.23.1.0.dylib
  Referenced from: <6CD8A217-53CD-3A01-A392-CEC3767C881B> /Users/sichong/anaconda3/envs/smk_dev/lib/python3.11/site-packages/google/protobuf/pyext/_message.cpython-311-darwin.so
  Reason: tried: '/Users/sichong/anaconda3/envs/smk_dev/lib/python3.11/site-packages/google/protobuf/pyext/../../../../../libprotobuf.23.1.0.dylib' (no such file), '/Users/sichong/anaconda3/envs/smk_dev/lib/python3.11/site-packages/google/protobuf/pyext/../../../../../libprotobuf.23.1.0.dylib' (no such file), '/Users/sichong/anaconda3/envs/smk_dev/bin/../lib/libprotobuf.23.1.0.dylib' (no such file), '/Users/sichong/anaconda3/envs/smk_dev/bin/../lib/libprotobuf.23.1.0.dylib' (no such file), '/usr/local/lib/libprotobuf.23.1.0.dylib' (no such file), '/usr/lib/libprotobuf.23.1.0.dylib' (no such file, not in dyld cache)
```
I've confirmed that installing `cloudpathlib-s3` alone (both 0.13 and 0.14) works just fine. But as soon as `google-core-api` is installed to the conda env, above error starts appearing.

**Comment by SichongP** [comment]
Actually, the error persists even after installing `cloudpathlib-gs`. 

I've tried in a fresh conda env with `cloudpathlib-gs` only and I'm getting the same error with every version of cloudpathlib

**Comment by SichongP** [comment]
I was able to fix this error by downgrading `protobuf` from `4.23.1` to `4.21.12`
